import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding.x = 15
padding.y = 15
opacity = 0.95

[font]
normal.family = "Source Code Pro Medium"
bold.family = "Source Code Pro"
italic.family = "Source Code Pro"
bold_italic.family = "Source Code Pro"
size = 13

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = 0
mods = "Control"
